### ISSUE TITLE
🐛 HTTP error when trying to compare with URL

### ISSUE THREAD

**Issue by fdornelasx** [policratus/pupyl#116]
**Describe the bug**

**To Reproduce**
1. up your server with:
comment: inside of the directory aps I put 3 jpeg imgs.

```
from pupyl.search import PupylImageSearch
from pupyl.web import interface

SEARCH = PupylImageSearch()

SEARCH.index(
    'aps'
)

interface.serve()
```

2. use the search with some public img from the internet.
suggestion: [https://i5.walmartimages.com/asr/9cd67e8a-a6be-4544-9159-b8ef0a192510_2.3a4169a1e12daa021a808b64d70f27eb.jpeg](url)
3. at this moment you will face some error like:

- pupyl.duplex.exceptions.FileIsNotImage, or
- urllib.error.HTTPError: HTTP Error 403: Forbidden

**Expected behavior**
The platform should return to the search screen, but it stops on a blank page.

**Desktop :**
 - OS: MacOS
 - Chrome 
 - 95.0

**Additional context**
Change urllib to python requests module, it will solve all your problems. 
urllib could be more fast sometimes, but with concerns like that.

**Comment by policratus** [comment]
Hey @fdornelasx, how's it going? Thanks for reporting.

We're trying to reproduce your issue, without success. Which version of `pupyl` are you using? We just tried to reproduce with the latest stable version (`0.12.4`), but we haven't any problem, using code pretty similar of the one that you've given:

```python
from pupyl.search import PupylImageSearch
from pupyl.web import interface

SEARCH = PupylImageSearch()

SEARCH.index('~/Downloads/images')

[*SEARCH.search('https://i5.walmartimages.com/asr/9cd67e8a-a6be-4544-9159-b8ef0a192510_2.3a4169a1e12daa021a808b64d70f27eb.jpeg')]

> [2, 1, 0]

[*SEARCH.search('https://i5.walmartimages.com/asr/9cd67e8a-a6be-4544-9159-b8ef0a192510_2.3a4169a1e12daa021a808b64d70f27eb.jpeg', return_metadata=True)]

> [{'original_file_name': '1635387875617a09e3b3e50_1635387875_3x2_md.jpg',
  'original_path': '/home/policratus/Downloads/images',
  'original_file_size': '39K',
  'original_access_time': '2021-11-05T19:00:36',
  'id': 2,
  'internal_path': '/tmp/pupyl/0/2.jpg'},
 {'original_file_name': 'GettyImages-1316152329.jpg',
  'original_path': '/home/policratus/Downloads/images',
  'original_file_size': '221K',
  'original_access_time': '2021-11-05T19:00:36',
  'id': 1,
  'internal_path': '/tmp/pupyl/0/1.jpg'},
 {'original_file_name': 'Saweetie-e-Anitta.jpg',
  'original_path': '/home/policratus/Downloads/images',
  'original_file_size': '115K',
  'original_access_time': '2021-11-05T19:00:36',
  'id': 0,
  'internal_path': '/tmp/pupyl/0/0.jpg'}]

interface.serve()
```

![Screenshot from 2021-11-05 16-20-07](https://user-images.githubusercontent.com/827563/140566883-042d24f2-d9a5-4dab-a1f5-d9d36764c4a3.png)
![Screenshot from 2021-11-05 16-21-14](https://user-images.githubusercontent.com/827563/140566896-efc0694a-5414-48e7-b62c-3716a6c3ca10.png)

@fdornelasx, could you please give us more information about your stack? Thanks in advance!

**Comment by policratus** [comment]
🛑 @fdornelasx, issue closed due to lack of interaction.

**Comment by fdornelasx** [comment]
Sorry for the late.

You should try to find based on a web url and try to submit.



Em sex., 12 de nov. de 2021 às 10:13, policratus ***@***.***>
escreveu:
