### ISSUE TITLE
✨ Search image to CLI and (optionally) copy matches to a folder

### ISSUE THREAD

**Issue by policratus** [policratus/pupyl#123]
### Discussed in https://github.com/policratus/pupyl/discussions/122 and https://github.com/policratus/pupyl/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **rleaver152** November 26, 2021</sup>
It would be great to be able to batch interrogate the database using a Bash script (within the virtual environment)  and the CLI to:

eg input (eg -in flag)  search image to CLI and copy matches (within a defined match value) to a (-o flag)  named folder</div>

* Expose search mechanism on `CLI` interface;
* Optionally give the option to export results image files to a folder.

### Examples
```shell
# Returning only image ids
pupyl --data_dir /path/to/your/data/dir search /path/to/image/query.jpg
> 129
685
346
524
```
```shell
# Returning metadata
pupyl --data_dir /path/to/your/data/dir search /path/to/image/query.jpg --metadata
> {
       "id": 129,
       "internal_path": "/tmp/pupyl/0/129.jpg",
       "original_access_time": "2021-09-17T13:42:33",
       "original_file_name": "517791629_f05c1518bd.jpg",
       "original_file_size": "52K",
       "original_path": "/tmp/tmpn6duarq6"
   }
   {
       "id": 685,
       "internal_path": "/tmp/pupyl/0/685.jpg",
       "original_access_time": "2021-09-17T13:42:34",
       "original_file_name": "427954022_a072d55df9.jpg",
       "original_file_size": "65K",
       "original_path": "/tmp/tmpn6duarq6"
   }
   ...
```
```shell
# Copying results to folder
pupyl --data_dir /path/to/your/data/dir search /path/to/image/query.jpg --results /path/to/output/results
```

**Comment by rleaver152** [comment]
Looks great.    Maybe add "--threshold [0.5]  "   or similar to stop matches which are all lower than desired being copied?

**Comment by policratus** [comment]
Great @rleaver152! The issue regarding a `--threshold` parameter is that will give users the responsibility to deal with an asymmetric metric which are distances (how `pupyl` calculates similarities). 

My suggestion is to use a flag like `--top [int]`, which stop returning matches after the top _n_ matches are satisfied. For instance:

```shell
# Returns the first 6 matches
pupyl --data_dir /path/to/your/data/dir search /path/to/image/query.jpg --top 6
```

**Comment by rleaver152** [comment]
That would be perfect and solve the requirement.
