### ISSUE TITLE
🐛Indexing duplications

### ISSUE THREAD

**Issue by 92amartins** [policratus/pupyl#63]
**Describe the bug**
I'm afraid in some cases pupyl is indexing the same image more than once.

**To Reproduce**
1. Collect few images (e.g. 10)
1. Run the example code from README.
1. See error

**Expected behavior**
On the screenshot below I expected `cars` to appear only once.

**Screenshots**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/4500163/102019229-03c7c080-3d51-11eb-9ebb-d799412bd06c.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser safari 14.0.1
 - Python 3.8.6
 - Pupyl Version 0.10.4

**Additional context**
Folder Structure:
```
.
├── images
│   ├── batman.jpg
│   ├── captain.jpg
│   ├── cars.jpg
│   ├── flash.jpg
│   ├── green.jpg
│   ├── inside_out.jpg
│   ├── monsters.jpg
│   ├── nemo.jpg
│   ├── superman.jpg
│   └── toy.jpg
└── images.py
```

```
# image.py
from pupyl.search import PupylImageSearch
from pupyl.web import interface


SAMPLES = 'images'

SEARCH = PupylImageSearch()

SEARCH.index(SAMPLES)

interface.serve()
```

**Comment by policratus** [comment]
First of all, thank you @92amartins for reporting this. A question: did you ran the method `PupylImageSearch.index()` twice on the same source (in this case, a directory)?

**Comment by 92amartins** [comment]
You're welcome.

Yes :(

In the first run, I had the images at the same directory as `images.py`. That caused `pupyl` to try to index the .py file raising `FileIsNotImage` exception. In spite of that, probably indexed a few files (alphabetically?) before raising the exception.

For the second run,  I moved all the images to a separate folder, then ran the script with no issues.

I think that's why it got duplicated.

Maybe `pupyl` could have a mechanism for preventing indexing duplicated images, but as I'm not sure if this is a main case or edge case, I'll leave it up to you.

Feel free to close the issue, as I clearly made a misuse.

**Comment by policratus** [comment]
> You're welcome.
> 
> Yes :(
> 
> In the first run, I had the images at the same directory as `images.py`. That caused `pupyl` to try to index the .py file raising `FileIsNotImage` exception. In spite of that, probably indexed a few files (alphabetically?) before raising the exception.
> 
> For the second run, I moved all the images to a separate folder, then ran the script with no issues.
> 
> I think that's why it got duplicated.
> 
> Maybe `pupyl` could have a mechanism for preventing indexing duplicated images, but as I'm not sure if this is a main case or edge case, I'll leave it up to you.
> 
> Feel free to close the issue, as I clearly made a misuse.

Well, we do have a bug here: `pupyl` should only try to index supported image files, not all files in a source. I'll open a issue to fix this bug.

The mechanism that you described seems pretty useful to avoid any duplications and it will be implemented as an optional parameter during an index process. This mechanism is nice but creates a little overhead during the index, so will be up to the user choosing it.
